# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneAi < Formula
  desc "AI-powered command-line tool for Crossplane resource management"
  homepage "https://github.com/patradinesh/crossplane-ai"
  version "0.1.0-alpha.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.3/crossplane-ai_Darwin_x86_64.tar.gz"
      sha256 "9469e0260c978c7dfd3c96c861e31f5c7f2d4a31d9ccc8ca264d90f0302795d0"

      def install
        bin.install "crossplane-ai"
      end
    end
    on_arm do
      url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.3/crossplane-ai_Darwin_arm64.tar.gz"
      sha256 "6b6d7c77e3f877d2823f9f7f7d590f60c65b1e0a83cd3e970bd8eb05618c491b"

      def install
        bin.install "crossplane-ai"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.3/crossplane-ai_Linux_x86_64.tar.gz"
        sha256 "b963abb00b5f27efe16222125a0085adb1b690930ceddcd61ba6d0d6e040bf2f"

        def install
          bin.install "crossplane-ai"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.3/crossplane-ai_Linux_arm64.tar.gz"
        sha256 "97d6822b3e9c8096dc807bf8004ca3eb1d7163466d1b5dfeba8ab6d06aa32936"

        def install
          bin.install "crossplane-ai"
        end
      end
    end
  end

  test do
    system "#{bin}/crossplane-ai --help"
  end
end
