# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneAi < Formula
  desc "AI-powered command-line tool for Crossplane resource management"
  homepage "https://github.com/patradinesh/crossplane-ai"
  version "0.1.0-alpha.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.4/crossplane-ai_Darwin_x86_64.tar.gz"
      sha256 "1de1792604062237af867e6835fe5b69d5ba48b2b4f0063914bd95a1d726c89f"

      def install
        bin.install "crossplane-ai"
      end
    end
    on_arm do
      url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.4/crossplane-ai_Darwin_arm64.tar.gz"
      sha256 "e79644606a32a61b059ba1fb623e6844bdc36ac9467e504a6eb08679ce5cddf4"

      def install
        bin.install "crossplane-ai"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.4/crossplane-ai_Linux_x86_64.tar.gz"
        sha256 "f3a06fc4626bc9308e87a1d6d0726ff69e849680ae2dfb8ee9b704d2ce3b2328"

        def install
          bin.install "crossplane-ai"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.4/crossplane-ai_Linux_arm64.tar.gz"
        sha256 "d67d7fb7fdee67b127d2d1222ad0aa530843552d74bb40a4ebb086d696ec6468"

        def install
          bin.install "crossplane-ai"
        end
      end
    end
  end

  test do
    system "#{bin}/crossplane-ai --help"
  end
end
