# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneAi < Formula
  desc "AI-powered command-line tool for Crossplane resource management"
  homepage "https://github.com/patradinesh/crossplane-ai"
  version "0.1.0-alpha.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.2/crossplane-ai_Darwin_x86_64.tar.gz"
      sha256 "41592cc6ea53f48090310a8a2de7253fde7ae7602fb12620205f00c81763c5ca"

      def install
        bin.install "crossplane-ai"
      end
    end
    on_arm do
      url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.2/crossplane-ai_Darwin_arm64.tar.gz"
      sha256 "8cab3d4c9ff78bbb3ec3bbab33baf2b443fc73602773614e2d42ce85d7e57b86"

      def install
        bin.install "crossplane-ai"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.2/crossplane-ai_Linux_x86_64.tar.gz"
        sha256 "5be4ab69081e8bc6daf135a897d946558e1973ae74d533a099099863b4f82ef9"

        def install
          bin.install "crossplane-ai"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/patradinesh/crossplane-ai/releases/download/v0.1.0-alpha.2/crossplane-ai_Linux_arm64.tar.gz"
        sha256 "3bb69adde5b78a1a53441eca576e7fa9ac7e2b11c407e326470d036c49681239"

        def install
          bin.install "crossplane-ai"
        end
      end
    end
  end

  test do
    system "#{bin}/crossplane-ai --help"
  end
end
